### ISSUE TITLE
HTTP Method 방식 변경

### ISSUE THREAD

**Issue by rave189** [ppcomp/knu-notice-client#117]
기존 GET /accounts/device에서 보내는 Id값에 특수문자가 포함되어 Spring에서 IllegalException이 발생.
따라서 기존 방식에서 URL Safe한 방식인 POST 방식으로 변경하여 요청
POST /accounts/device-info
{
   "id": "string",
   "id_method": "string",
   "keywords": [
      "keyword": "string"
   ],
   "subscriptions": [
      "subscription": "string"
   ],
   "alarm_switch_sub": true,
   "alarm_switch_key": true
}

기존 Device 테이블의 Keyword와 Subscription이 정규화를 지키지 않고 저장되어있음.
정규화를 지키기 위해 Keyword 테이블, Subscription 테이블로 정보를 옮김.
이에 기존 PUT 메소드의 keyword와 subscription의 데이터 타입을 변경.
PUT /accounts/device
{
   "id": "string",
   "id_method": "string",
   "keywords": [
      "keyword": "string"
   ],
   "subscriptions": [
      "subscription": "string"
   ],
   "alarm_switch_sub": true,
   "alarm_switch_key": true
}

**Comment by qwlake** [comment]
https://github.com/ppcomp/knu-notice-client/pull/118 에서 처리 완료
